name: Test

on:
  push:
    branches: ["develop", "feat/*"]
  pull_request:
    branches: ["develop", "feat/*"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Node
        # uses: denoland/setup-deno@v1
        uses: actions/setup-node@v3
        with:
          node-version: v20.11

     
      - name: Install Dependencies
        run: npm install --force

      - name: Run tests
        run: npm run test:e2e
